### ISSUE TITLE
New Member Recruiting -- Presentation materials

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#7]
Subtask of #6 

Design ways and materials (presentation, flyer, email, ...) to introduce/spread HiCodingClub to new members. 

Focus on the ways and content of the various forms of the presentation and do not worry about the beautification aspect of the material. We will have designers to make them look beautiful.

**Expected Output:**
- present, in the form of a document, the ways we can introduce/spread HiCodingClub, the content we need to write, and how we can use the mean.
- During the next board meeting, talk to the rest of the team about the advertising strategies.

**Example of a part of the final document:**

Way 1: Flyer
Content: 
- Picture of HiCodingClub
- Logo
- Website Address
- Introductory paragraph: HiCodingClub is a club/nonprofit that focuses on ...
To spread: pass around in school, ...

Way 2: Poster
Content:
...

**Comment by andrewnpaul** [comment]
Way 1: Speaking
Content: Hello everyone, I would like to invite you to HiCodingClub: our small club that works on various projects. It's great for anyone that aspires to become a developer in the future and wants some experience outside of school or this club. Right now we only have a few members and we need more so please don't hesitate to apply if you're interested. Here's what we've worked on so far and what we're planning to do in the future...
To spread: Ask your high school's programming club if we can advertise our club in one of the club sessions.

Way 2: Email
Content: Email containing description and website address.
To spread: (As a supplement to the above method) Ask your high school's programming club to send all members an email about HCC after we've introduced HCC in a club session.

Way 3: Instagram / Facebook / other social media
Content: HiCodingClub for aspiring developers! Please visit link in profile for more details
To spread: Share this in your instagram story or facebook feed or other social media. People won't be able to read long descriptions because stories only show up a few seconds so make sure it's eye catching.

Way 4: Electronic poster
Content: This should be more detailed than the above since people will actually read it. Should include image and thorough description.
To spread: Text this flyer to your friends and group chats on iMessage.

Way 5: Poster
Content: Picture of HCC, logo of HCC, website address, introductory paragraph
To spread: Ask your school and your local library if you can put posters on the walls to advertise our club.

**Comment by andrewnpaul** [comment]
https://docs.google.com/document/d/1fgoKPEv6e-oSDyRweJo2suBwONyv7PTUln70L_vaVVg/edit
